---
title: "Homework Quiz"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    css: ../../../../styles.css
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. I want to predict how well 6 year-olds are going to do in their final school exams. Using the following variables am I likely under-fitting, fitting well or over-fitting? Postcode, gender, reading level, score in maths test, date of birth, family income.


2. If I have two models, one with an AIC score of 34,902 and the other with an AIC score of 33,559 which model should I use?


3. I have two models, the first with: r-squared: 0.44, adjusted r-squared: 0.43. The second with: r-squared: 0.47, adjusted r-squared: 0.41. Which one should I use?


4. I have a model with the following errors: RMSE error on test set: 10.3, RMSE error on training data: 10.4. Do you think this model is over-fitting?


5. How does k-fold validation work?


6. What is a validation set? When do you need one?


7. Describe how backwards selection works.


8. Describe how best subset selection works.


9. It is estimated on 5% of model projects end up being deployed. What actions can you take to maximise the likelihood of your model being deployed?


10. What metric could you use to confirm that the recent population is similar to the development population?


11. How is the Population Stability Index defined? What does this mean in words?


12. Above what PSI value might we need to start to consider rebuilding or recalibrating the model


13. What are the common errors that can crop up when implementing a model?


14. After performance monitoring, if we find that the discrimination is still satisfactory but the accuracy has deteriorated, what is the recommended action?


15. Why is it important to have a unique model identifier for each model?


16. Why is it important to document the modelling rationale and approach?


