---
title: "Introduction to `ggplot2` homework"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    css: ../../../styles.css
    pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)
```

# Homework Info

This homework recaps what you learnt in class today. 

You'll be looking at the `backpack` dataset contained within the `CodeClanData` package using tidyverse. You'll need to load the appropriate packages first.     

**In all plots you make, ensure your labels are appropriate. You also must write down a short summary of what each plot tells you in order to meet MVP.**  

**Make sure you create a new project in which to do this homework!**


# MVP

<br>

**Question 1.**  

Load in the libraries you need, and look at the `backpack` data. Take note of variable names and dimensions.   


**Question 2.**

What is the distribution of backpack weights that students are carrying? Choose an appropriate graph to show the distribution. 


**Question 3.**  

Are there differences in backpack weight between sex?   


**Question 4.**  

What is the relationship between body weight and backpack weight?


**Question 5.**  

Is this relationship different between men and women? Choose an appropriate plot and interpret your findings.  


**Question 6.**  

What **proportion** of students report back pain?   


**Question 7.**  

Is this proportion different between men and women? 


**Question 8.**  

Now you've investigated your data separately, create plots to describe the relationship between backpack weight, body weight, gender and reported backpain.

Try both `backpack_weight` and `body_weight` as well as the `ratio`.   

*Hint: faceting would be useful here*.   

# Extensions

<br>

**Question 1.** 

Does reported backpain differ across the year groups? Ignore year 0 in your data.  


**Question 2.** 

Is there a difference between how heavy the bags those in different years carry?


